var locationiq={};locationiq.key=null;var finalHost="https://tiles.locationiq.com"
locationiq.layerStyles={"Streets":"streets/vector","Satellite":"earth/raster","Hybrid":"hybrid/vector",};function locationiqLayerControl({layerStyles,...options}){this.options=options;if(layerStyles){locationiq.layerStyles=layerStyles;}
this.options.layers=Object.keys(locationiq.layerStyles);}
locationiqLayerControl.prototype={onAdd:function(map){this._map=map;this._container=document.createElement('div');this._container.className='liq-styles-ctrl-gl-menu maplibregl-ctrl maplibregl-ctrl-group';this._container.id='liq-styles-ctrl-gl-menu';this._container.addEventListener('contextmenu',(e)=>event.preventDefault?event.preventDefault():(event.returnValue=false));var layers=this.options.layers;this._layerButtons={};attribE=false;try{attribE=map.getContainer().querySelector('.maplibregl-ctrl-attrib');}catch(e){attribE=false;}
if(!attribE){this._map.addControl(new maplibregl.AttributionControl({compact:true}));}
var i=0;if(layers.length===1){this._map.setStyle(locationiq.getLayer(layers[0]));return this._container;}
for(i=0;i<layers.length;++i){const switchButton=window.document.createElement('input');switchButton.id=layers[i];switchButton.setAttribute('type','radio');switchButton.setAttribute('value',layers[i]);this._layerButtons[layers[i]]=switchButton;if(i==0){this._checkedLayer=layers[i];switchButton.checked=true;this._map.setStyle(locationiq.getLayer(layers[i]));}
const switchLabel=window.document.createElement("Label");switchLabel.setAttribute("for",layers[i]);switchLabel.innerHTML=layers[i];switchLabel.addEventListener('click',this._switchLayer.bind(this,layers[i]));this._container.appendChild(switchButton);this._container.appendChild(switchLabel);}
return this._container;},onRemove:function(){this._container.parentNode.removeChild(this._container);this._map=undefined;},_switchLayer:function(layer){this._map.setStyle(locationiq.getLayerConfigUrl(layer));this._radioSelector(layer);},_radioSelector:function(selection){this._layerButtons[this._checkedLayer].checked=false;this._layerButtons[selection].checked=true;this._checkedLayer=selection;}};locationiq.getLayer=locationiq.getLayerConfigUrl=function(layer){if(locationiq.layerStyles[layer]!==undefined){layerComponent=locationiq.layerStyles[layer];}else{console.log("Error, undefined theme: "+layer);}
var finalUrl=finalHost+"/v3/"+layerComponent+'.json?key='+locationiq.key;return finalUrl;}